Feature/354 Add Stream as content
nclient/NClient pull request #393
Opened 2021-12-24 17:35 UTC by Kingmidas74

2021-12-24 17:37 UTC, Kingmidas74 commented
I've added Stream as option to Content and now not all tests are passed.

2021-12-24 22:35 UTC, smolchanovsky requested changes

2021-12-24 22:35 UTC, smolchanovsky commented on src/NClient.Providers/NClient.Providers.Transport.SystemNetHttp/SystemNetHttpTransportRequestBuilder.cs
> +                httpRequestMessage.Content = new StreamContent(request.Content.GetContentAsStream());
Why wrap in `StreamContent`?

2021-12-24 22:35 UTC, smolchanovsky commented on src/NClient/NClient.Abstractions/Providers/Transport/Common/Content.cs
> +        public Content(byte[]? bytes = null, Stream? streamContent = null, string? encoding = null, IMetadataContainer? headerContainer = null)
Why do we need bytes if there is a stream now?

2021-12-24 22:37 UTC, smolchanovsky commented
> I've added Stream as option to Content and now not all tests are passed.

Why don't they pass? What error?

2022-02-15 23:06 UTC, smolchanovsky approved these changes

2022-04-16 00:02 UTC, smolchanovsky approved these changes

2022-04-16 00:10 UTC, merged