Features/417 WithAuthorization methods
nclient/NClient pull request #435
Opened 2022-04-17 19:44 UTC by smolchanovsky

2022-04-18 11:18 UTC, Kingmidas74 commented
I think we should redesign this method.
For ex: 
UseCredentials()

Also add some  options for ntlm etc..

2022-04-18 11:18 UTC, Kingmidas74 commented
I think we should redesign this method.
For ex: 
UseCredentials()

Also add some  options for ntlm etc..

2022-04-18 11:28 UTC, Kingmidas74 requested changes
I didn't see anything about ICredentials for use log\pass\domain. Or NTLM or etc...

2022-04-18 12:14 UTC, Kingmidas74 commented on src/NClient/NClient.Standalone/Client/Authorization/CompositeAuthorization.cs
> +                if (tokens is not null)
Why you don't use ?? operator?

2022-07-08 15:50 UTC, smolchanovsky commented on src/NClient/NClient.Abstractions/Building/Factory/INClientFactoryOptionalBuilder.cs
> +        INClientFactoryOptionalBuilder<TRequest, TResponse> WithTokenAuthorization(ITokens tokens);
The method must have an IAuthorizationProvider type parameter instead of ITokens

2022-07-08 15:58 UTC, smolchanovsky commented
> I didn't see anything about ICredentials for use log\pass\domain. Or NTLM or etc...

I started a separate issue https://github.com/nclient/NClient/issues/437 for this. It is quite complex and requires a design discussion

2022-07-11 08:27 UTC, Kingmidas74 approved these changes

2022-07-11 08:36 UTC, merged